name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for Jira Ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://cspjira.igt.com/jira/projects/PEIT/issues/PEIT-%ticketNumber%'
          ticketPrefix: 'PEIT'
          titleRegex: '^PEIT-(?<ticketNumber>\d+)'
          branchRegex: '^PEIT-(?<ticketNumber>\d+)'
          bodyRegex: 'PEIT-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(:cspjira.igt.com)(\/jira)\/(PEIT\-)(?<ticketNumber>\d+)'